- name: 准备kube-controller-manager 证书签名请求
  template: 
    src: kube-controller-manager-csr.json.j2 
    dest: "{{ base_dir }}/ssl/kube-controller-manager-csr.json"

- name: 创建 kube-controller-manager证书与私钥
  shell: |
      cfssl gencert \
      -ca=ca.pem \
      -ca-key=ca-key.pem \
      -config=ca-config.json \
      -profile=kubernetes kube-controller-manager-csr.json | cfssljson -bare kube-controller-manager
  args:
    chdir: "{{ base_dir }}/ssl"

- name: 设置集群参数
  shell: | 
        kubectl config set-cluster kubernetes \
        --certificate-authority=ca.pem \
        --embed-certs=true \
        --server=https://127.0.0.1:6443 \
        --kubeconfig={{ base_dir }}/ssl/kube-controller-manager.kubeconfig
  args:
    chdir: "{{ base_dir }}/ssl"

- name: 设置认证参数
  shell: |
        kubectl config set-credentials system:kube-controller-manager \
        --client-certificate=kube-controller-manager.pem \
        --client-key=kube-controller-manager-key.pem \
        --embed-certs=true \
        --kubeconfig={{ base_dir }}/ssl/kube-controller-manager.kubeconfig
  args:
    chdir: "{{ base_dir }}/ssl"

- name: 设置上下文参数
  shell: |
        kubectl config set-context default \
        --cluster=kubernetes \
        --user=system:kube-controller-manager \
        --kubeconfig={{ base_dir }}/ssl/kube-controller-manager.kubeconfig
  args:
    chdir: "{{ base_dir }}/ssl"

- name: 选择默认上下文
  shell: |
        kubectl config use-context default \
        --kubeconfig={{ base_dir }}/ssl/kube-controller-manager.kubeconfig