- name: 准备kubectl使用的admin证书签名请求
  template: 
    src: admin-csr.json.j2 
    dest: "{{ base_dir }}/ssl/admin-csr.json"

- name: 创建admin 证书与私钥
  shell: |
      cfssl gencert \
      -ca=ca.pem \
      -ca-key=ca-key.pem \
      -config=ca-config.json \
      -profile=kubernetes \
      admin-csr.json | cfssljson -bare admin
  args:
    chdir: "{{ base_dir }}/ssl"

- name: 设置集群参数
  shell: |
    kubectl config set-cluster {{ CLUSTER_NAME }} \
      --certificate-authority=ca.pem \
      --embed-certs=true \
      --server=https://127.0.0.1:6443 \
      --kubeconfig=admin.kubeconfig
  args:
    chdir: "{{ base_dir }}/ssl"

- name: 设置客户端认证参数
  shell: | 
    kubectl config set-credentials admin \
    --client-certificate=admin.pem \
    --embed-certs=true \
    --client-key=admin-key.pem \
    --kubeconfig=admin.kubeconfig
  args:
    chdir: "{{ base_dir }}/ssl"

- name: 设置上下文参数
  shell: | 
    kubectl config set-context default \
    --cluster={{ CLUSTER_NAME }} \
    --user=admin \
    --kubeconfig=admin.kubeconfig

- name: 选择默认上下文
  shell: kubectl config use-context default --kubeconfig=admin.kubeconfig