- name: 准备kube-proxy 证书签名请求
  template: 
    src: kube-proxy-csr.json.j2 
    dest: "{{ base_dir }}/ssl/kube-proxy-csr.json"

- name: 创建 kube-proxy证书与私钥
  shell: | 
        cfssl gencert \
        -ca=ca.pem \
        -ca-key=ca-key.pem \
        -config=ca-config.json \
        -profile=kubernetes \
        kube-proxy-csr.json | cfssljson -bare kube-proxy
  args:
    chdir: "{{ base_dir }}/ssl"


- name: 设置集群参数
  shell: |
        kubectl config set-cluster kubernetes \
        --certificate-authority=ca.pem \
        --embed-certs=true \
        --server={{ KUBE_APISERVER }} \
        --kubeconfig={{ base_dir }}/ssl/kube-proxy.kubeconfig
  args:
    chdir: "{{ base_dir }}/ssl"


- name: 设置客户端认证参数
  shell: |
        kubectl config set-credentials kube-proxy \
        --client-certificate=kube-proxy.pem \
        --client-key=kube-proxy-key.pem \
        --embed-certs=true \
        --kubeconfig={{ base_dir }}/ssl/kube-proxy.kubeconfig
  args:
    chdir: "{{ base_dir }}/ssl"


- name: 设置上下文参数
  shell: |
        kubectl config set-context default \
        --cluster=kubernetes \
        --user=kube-proxy \
        --kubeconfig={{ base_dir }}/ssl/kube-proxy.kubeconfig
  args:
    chdir: "{{ base_dir }}/ssl"


- name: 选择默认上下文
  shell: |
      kubectl config use-context default \
      --kubeconfig={{ base_dir }}/ssl/kube-proxy.kubeconfig