- name: prepare some dirs
  file: name={{ item }} state=directory
  with_items:
  - "{{ bin_dir }}"
  - "{{ ca_dir }}"
  - "/etc/etcd/ssl"    # etcd 证书目录

- name: prepare some dirs
  file: 
    name: /var/lib/etcd 
    state: directory
    mode: 0700

- name: 下载etcd二进制文件
  copy: 
    src: "{{ item }}" 
    dest: "{{ bin_dir }}/{{ item }}"
    mode: 0755
  with_items:
  - etcd
  - etcdctl


- name: 拷贝cfssl工具
  copy: 
    src: "/usr/local/bin/{{ item }}" 
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
  with_items:
    - cfssl
    - cfssljson


- name: 分发证书相关
  copy: 
    src: "{{ base_dir }}/ssl/{{ item }}"
    dest: "{{ ca_dir }}/{{ item }}"
  with_items:
  - ca.pem
  - ca-key.pem
  - ca-config.json

- name: 创建etcd证书请求
  template: 
    src: etcd-csr.json.j2
    dest: /etc/etcd/ssl/etcd-csr.json


- name: 创建 etcd证书和私钥
  shell: cfssl gencert \
        -ca={{ ca_dir }}/ca.pem \
        -ca-key={{ ca_dir }}/ca-key.pem \
        -config={{ ca_dir }}/ca-config.json \
        -profile=kubernetes etcd-csr.json | cfssljson -bare etcd
  args:
    chdir: /etc/etcd/ssl


- name: 创建etcd的systemd unit文件
  template: 
    src: etcd.service.j2 
    dest: /etc/systemd/system/etcd.service

- name: 开机启用etcd服务
  shell: systemctl enable etcd
  ignore_errors: true

- name: 开启etcd服务
  shell: systemctl daemon-reload && systemctl restart etcd
  ignore_errors: true

- name: 以轮询的方式等待服务同步完成
  shell: "systemctl status etcd.service|grep Active"
  register: etcd_status
  until: '"running" in etcd_status.stdout'
  retries: 8
  delay: 8
